mozilla-iam/sso-dashboard

dashboard/app.py

This is in reference to bugzilla bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1362307
/gmail => redirects but /gmail/ does not.  Fixing this by adding a vanity route with trailing slash for each URL and some logging for 404s to see if anything else is missed.

update router to include vanity urls with trailing slash

---

docs/alert-center.md

Feel free to squash the commits.
This follows the standard at https://wiki.mozilla.org/Security/Standard_Levels - but I've also added my grain of salt.
In particular note the addition of a "remember" button - I know this button was needed for such a system to be successful elsewhere.
Likewise, but did not add yet: we most likely want the users to be able to subscribe to alerts by email, sms, irc, slack in the future

Standardification with standard levels

---

dashboard/app.py

We now serve Mozillians avatars from a different URL, so they aren't currently loading in the dashboard

Add media.mozillians.org to img-src CSP

---

.travis.yml
dashboard/app.py
dashboard/auth.py
dashboard/config.py
dashboard/op/yaml_loader.py
dashboard/s3.py
dashboard/static/js/base.js
dashboard/templates/dashboard.html
dashboard/user.py
dashboard/utils.py
dashboard/vanity.py
requirements.txt
tests/data/userinfo.json
tests/test_config.py
tests/test_user.py
tests/test_yaml_loader.py

This is largely prep work for adding alerts to the dashboard.
* Removes a lot of unused code. 
* Makes yaml loader more idiomatic python.
* pep8 all the things and get tests passing ( no longer block CI for non admins )
* move to bespoke version of oic.
* move to kangs updates to flask-pyoidc in order to support session refresh ( though we will likely still go with auth proxy in the near future. 
* Prep everything for a move to python3.6 ( only forking and fixing flask-secure-headers remains )

light refactor of a few facilities prior to adding alerts

---

dashboard/models/alert.py

The comparison wasn't handling the case where a dot release version exists. Handles dot release, if exists, even if the user agent doesn't contain it.

Issue 173: compare version major and minor and dot versions

---

buildspec.yml

Users in the Taipei region and TPE1 office are unable to view the SSO dashboard after logging in
Some users with unicode chars in their profile can not log in.  This temporarily patches this.
CHG0012101

hotfix for bug 1399778

---

dashboard/app.py
dashboard/auth.py
dashboard/config.py
dashboard/templates/forbidden.html
requirements.txt

This continues on the work gene did yesterday but moves the code from the route into the dashboards object model.  Public cert is now base64 encoded in credstash instead to resolve LF inconsistency.  
Additionally error message logic has been moved into a method to simplify the logic in the error message views and make the code overall more testable.

Enrich error message page

---

dashboard/static/css/base.scss
dashboard/templates/dashboard.html

I've made this change, so that they are easier to use by screenreader and keyboard users.
This is what I've done:
* we've added ‘accessible text’ of “Dismiss” to the buttons. People with a screenreader can't see the X, but they will hear 'Dismiss'. I've made the actual X invisible to screenreaders (so that they don't hear 'X') using the `aria-hidden` attribute
* now that we use a `button` element in HTML, the button can be focused and interacted with using a keyboard (and it gets announced as 'button' by screenreaders; win win win)

Use real buttons with text as close buttons

---

dashboard/templates/dashboard.html

This adds the date of when the alert was created to the alert banner message. The date is already present in the alert notification center, so no need to change that.

Add date to alert banner message

---

dashboard/templates/forbidden.html

Since users (including volunteers) who end up doing something wrong in the authentication process get redirected to `/forbidden`, putting the "Need Help?" link behind an LDAP authentication screen makes it rather useless.
While Discourse does also require users to authenticate to post through the web interface, it's also possible to create a post through email with no account set up. For a user hitting https://discourse.mozilla.org/c/iam, they'd need to press the envelope icon... which they might not realise they can use without being authenticated.
We could, instead, make the "Need Help?" link a `mailto:` link for the Discourse category, but then users may not understand that their post is going to be public.
Instead of that, it's possible for us to set up a private group inbox in …

change forbidden "Need Help?" link to discourse

---

dashboard/app.py
dashboard/static/css/base.scss
dashboard/templates/dashboard.html

This links to the autologin settings page, currently live in NLX DEV.
A great addition would be to also pass the user's **email address** (as `user_email`) and **login method** (as `user_login_method`) as NLX DEV supports displaying those, but for that we'd need them to be in the user model.

Add link to NLX Auto-login Settings

---

dashboard/api/exceptions.py
dashboard/api/idp.py
dashboard/app.py
dashboard/models/alert.py
requirements.txt

Adds an alert API endpoint that uses standard auth0 bearer token based auth to retrieve counts of unacknowledged alerts by severity for a user.
```
curl --request GET \
--url http://localhost:5000/api/v1/alert?user_id=ad%7CMozilla-LDAP%7Cakrug \
--header 'authorization: Bearer $BEARER'
```
Returns dict of number of unack'ed alerts.
```
{
"alerts": {
"high": 1,
"low": 0,
"maximum": 0,
"medium": 1
}
}
```

add alert api endpoint

---

dashboard/auth.py

Add a message indicating that you may have to log out of Firefox Account and back in again. This is due to possible caching delays in Firefox Account, which will be most likely resolved in the future. In the mean time, this should help the few users that could run into this. It's thanksfully fairly rare.

Add a message indicating that you may have to log out of Firefox Account and back in again. 

---

dashboard/config.py

I need to be able to override this `SERVER_NAME` value when running the Development environment in Kubernetes. This simple change should support that
without impacting anything else.
NOTE: "Restrict who can push to this branch" is effectively the …

check env for server name before setting default value

---

dashboard/models/alert.py
requirements.txt
tests/test_alerts.py

* Auto purge alerts older than 7 days when pulling back from the alerts table.
* Improve coverage of alerts class
* Add global secondary index to mocks

Purge old alerts

---

dashboard/static/css/base.scss

This expands the width of the alert messages, so the updated geomodel summary will not get chopped up into 2 lines.

Modify alert messages witdh

---

dashboard/auth.py

In a [Discourse comment](https://discourse.mozilla.org/t/2fa-cannot-be-mandatory/30352/21?u=hmitsch) we saw that the `secure account` terminology is prone to misinterpretation.
This PR suggests to make the wording less controversial while maintaining clear next steps for users to avoid getting trapped in a dead end.

Remove secure account terminology

---

ansible/roles/dashboard/files/nginx/nginx.conf
ansible/roles/dashboard/files/sso-dashboard.ini
dashboard/app.py
requirements.txt

This makes a few changes:
- Aggregates metrics across gunicorn workers
- Blocks access to /metrics in Nginx (another change on the ALB must occur)
- Adds new pip package for Prometheus
- Disables the Prometheus exporter (I need to work out some other issues)
Do NOT include the teams that may not (such as issue managers, …

enabling multiprocess for Prometheus export

---

cloudformation/us-west-2.yml

This changes the ACM certs in dev and prod us-west-2 to ACM certs
that are Route53 DNS validated instead of email validated

Change dev and prod us-west-2 ACM Arns

---

dashboard/csp.py

In the context of an XSS issue, where an attacker has gained control over JS in the context of this site, it could be possible for the attacker to force the browser to make http:// requests to 
ajax.googleapis.com, fonts.googleapis.com, and fonts.gstatic.com for various content, including script loads.
An attacker may wish to do this for a number of reasons:
1.) To leak secret material between those domains (unlikely in this specific context)
2.) To further compromise the integrity of JS load and chain that to gain full JS execution loaded over HTTP via MiTM attack.
I think this just helps us become more explicit that that "though shall load all CSP controlled content via HTTPS".
**WARNING**: I am not a sso dashboard developer, and this is just a good will type PR, please do test this …

Force https scheme for CSP policy values

---

k8s/templates/deployment.yaml

Kubernetes 1.16 deprecates `extensions/v1beta1` used in this deployment

Migrate API version to latest

---

dashboard/person.py

Since CISv1 is actively being deprecated, we comment out the call to /v1/profile (which eventually gets routed to CISv1). As the caller is wrapped with an except (https://github.com/mozilla-iam/sso-dashboard/blob/master/dashboard/app.py#L188-L197), the app still loads. This problem surfaces when you click on the upper right hand nav dropdown, where a "Name" and an avatar used to be displayed (https://github.com/mozilla-iam/sso-dashboard/blob/master/dashboard/templates/dashboard.html#L39-L43)
We'll need to update this function to reach out to the /v2 equivalent route in the person api.

Comment out code calling cisv1 person api endpoint

---

Makefile

Point at new Helm binary install location and upgrade Helm to get CodeBuild to work.
```bash
$ curl https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz                                                                                                                                                                                                                                                                                                                                                          
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message></Error>
```

Fix up setup-codebuild with helm binary that is available

---

requirements.txt

Thought it would be easy to pull in an update from dependabot but this ended up breaking the deploy and requiring updating [Flask-pyoidc](https://github.com/zamzterz/Flask-pyoidc/). That is a little more work than I can do right now but want to leave the repository in a deploy-able state.

Revert "Merge pull request #427 from mozilla-iam/dependabot/pip/oic-1.2.1

---

Makefile

This pulls a Docker ID and access token from SSM Parameter store for a dedicated
Docker user and logs in as that user to Docker Hub. This works around the issue
where anonymous API access to Docker Hub from AWS CodeBuild IP addresses results
in rate limiting the docker pulls of the Docker Base Image (e.g. centos)
Fixes #446
I haven't tested this as it's a CI fix but hopefully it works.

Add logic to login to Docker Hub

---

k8s/templates/ingress-controller.yaml
k8s/templates/ingress.yaml

```
Ingress                          sso-dashboard-prod   sso-dashboard                                        extensions/v1beta1                     networking.k8s.io/v1 (1.19.0)
Ingress                          sso-dashboard-dev    sso-dashboard                                        extensions/v1beta1                     networking.k8s.io/v1 (1.19.0)
Role                             sso-dashboard-dev    nginx-ingress-role                                   rbac.authorization.k8s.io/v1beta1      rbac.authorization.k8s.io/v1 (1.8.0)
Role                             sso-dashboard-prod   nginx-ingress-role                                   rbac.authorization.k8s.io/v1beta1      rbac.authorization.k8s.io/v1 (1.8.0)
RoleBinding                      sso-dashboard-dev …
```

chore(k8s): Migrate off beta apis

---

dashboard/oidc_auth.py

This PR stems from a slack request from csmith to better redirect users for assistance when a user is not in an application access group.

Update notingroup error message

---

dashboard/app.py
dashboard/logging.yml
requirements.txt

This PR reverts the previous addition of the gcp cloud logger and simply keeps the default logger active.  This allows all logging to pipe to stdout/stderr where cloudrun will send it to gcp logging.  Keeping the default logger active allows traceback stacks to be logged also.

Gcp logging

---

requirements.txt

This PR updates the Flask-pyoidc from 3.13.0 to 3.14.3.  This new version includes fixes [1] that better handles the OIDC work flow for Flask apps that reside behind firewalls and therefore likely are internally serving `http` from the backend.
[1] https://github.com/zamzterz/Flask-pyoidc/pull/169

Update Flask-pyoidc 3.13.0->3.14.3

---

dashboard/app.py

This is the beginning of the end for Alerts and Notifications in the SSO Dashboard.  This single commit disables the execution of the Rule engine.   There will be more PRs to follow that will gut the Rule engine itself to fully remove Alerts and Notifications related code from the SSO dashboard.  The intent to return the dashboard to a simple app tile display for users.
See IAM-1256

Disable the alert and notification engine

---

dashboard/oidc_auth.py

This should update the error text and messages displayed for users that formerly referenced Firefox Accounts.

Update references to Firefox Accounts -> Mozilla Accounts

---

Dockerfile

This is now needed because gunicorn is explicitly  watch that file. The container will fail to start no file exists.

Make user apps.yml exists in some form

---

clouddeploy/sso-dashboard-dev.template.yaml
clouddeploy/sso-dashboard-prod.template.yaml
clouddeploy/sso-dashboard-staging.template.yaml
dashboard/app.py
dashboard/config.py

Flask removed FLASK_ENV in v2.3.0 which was being checked on
the root flask route. (Thanks gcox!)
This commit fixes the environment varible for the seperate
environments and fixes where the variable is being sourced.
See: https://flask.palletsprojects.com/en/3.0.x/changes/#version-2-3-0

Fix app.env that was causing 500 error on / route

---

dashboard/op/yaml_loader.py

This is a follow-along to IAM-1399.
Commit 1 is primarily a pylint change, but there are cleanups that COULD be breaking but shouldn't be:
* removed py2-like `(object)` inheritance, forcing py3.
* removed a seemingly unused `_find` internal function.
Commit 2 smooshes `_has_vanity` into `vanity_urls` (more or less) removing the failure scenario that caused an outage.  (Before, "if there is a vanity_urls declaration I assume it's good". After: "if `vanity_urls` exists it has to be a list".

Application cleanup

---

.github/workflows/main.yml
.github/workflows/pull_requests_only.yml
.pre-commit-config.yaml
tests/test_user.py
tox.ini

Here we do the following:
* Make tox fail on missing interperters.
* Fix the TestUser test so the setup method handles errors and
initializes properly before the test.
* Instead of running black on pre-commit, we now run tox
locally which includes all linting and test suites include
black.  This now ensures the same linting and test that run
in Github Actions are executed locally before a commit.  In
addition, we run pre-commit in GHA so all linting and testing
is identical between what is run locally and in GHA.
* Fixed the existing main.yml GHA so the python 3.12 is set up
for tox to use.  This fixes the missing interperter issue that
was causing the skipped tox tests in the first place.
* Added a new GHA that only runs linting/tests on RPs.  This
will help catch things before landing …

Fix existing tests, pre-commit, and Github Actions

---

clouddeploy/sso-dashboard-dev.template.yaml
clouddeploy/sso-dashboard-prod.template.yaml
clouddeploy/sso-dashboard-staging.template.yaml

Recently, the Min/Max cloud run instances had been reduced in
an attempt to fix the failure causing the stale apps.yml data.
This commit increases the min instances to 1 for dev and 2 for
staging and prod.  The max is set to 3 for all 3 environments.
This also adjusts the gunicorn async workers to 3 which is based
on the fact, instances for all environments are set to 1vCpu.
Where n = vCpus, we get 2n + 1 as a basis for setting the
workers.  This can be adjust in the future if we ever change the
number of vCpus per instance.
Other things:
* Remove some unused ENVs
* Remove max-requests and max-requests-jitter

Increase Min/Max cloud run instances

---

ci/node-install.sh
package.json
tox.ini

(Sample size: 1)
Now (some output ommitted):
rm -rf .tox; time tox
tox  17.25s user 8.84s system 49% cpu 52.303 total
time tox
tox  1.72s user 0.38s system 86% cpu 2.436 total
Before (some output ommitted):
rm -rf .tox; time tox
tox  19.69s user 11.41s system 46% cpu 1:06.32 total
time tox
tox  3.57s user 3.64s system 24% cpu 29.537 total
It can go _faster_, but that'd come at the cost of having tox managing our dependencies when they change, so I opted not to do that. Though, we should keep that in our back pocket if we get to that point.

ci Don't always re-install dependencies, which speeds up successive builds

---

dashboard/api/idp.py
dashboard/models/tile.py
dashboard/models/user.py
dashboard/oidc_auth.py
dashboard/op/yaml_loader.py
dashboard/vanity.py

Instead of serializing only the error message, let's be friendly to our future selves and print the traceback as well.

Use logging.exception when we care about traceback

---

dashboard/app.py
requirements.txt
tests/models/test_user.py
tox.ini

Note that upon deploying all sessions will invalidated since the keys (read as: keys in Redis) will change.
Jira: [IAM-1468](https://mozilla-hub.atlassian.net/browse/IAM-1468)

Swap Flask-KVSession for Flask-Session

---

dashboard/__init__.py
dashboard/app.py
dashboard/config.py
dashboard/oidc_auth.py
env.example
requirements.txt
tests/test_oidc_auth.py

This PR adds/removes a couple of things:
* A documented `env.sample`
* An _updated_ `env.sample`, now shows the full keys we expect, along with some docs about where to get them
* Less dependencies (`everett`) -- this one did a bit of magic which I removed and implemented ourself (as a result it should be _painfully_ clear what's missing on startup)
* Use `OIDC_REDIRECT_URI` -- we set this environment variable but never use it
See individual commits for a better review story.

Be more explicit about configs and where they come from

---

dashboard/app.py
dashboard/templates/forbidden.html
dashboard/templates/signout.html

Flask-pyoidc supports provider discovery which we can make use of for auto-enabling the RP-Initiated Logout End Session Endpoint Discovery feature set.
When enabled the logout flow changes a bit and does not require a redirect in NLX, instead depending directly on Auth0 to complete the OIDC ceremony.
Prerequisites:
* `/logout` URL added as an accepted logout URL in the _client_ settings;
* RP-Initiated Logout End Session Endpoint Discovery enabled in _tenant_ settings;
* Toggling this in Auth0 _will require that you restart the application_.
Jira: [IAM-1493](https://mozilla-hub.atlassian.net/browse/IAM-1493)

Support RP-Initiated logout, further removing the need for NLX

---

dashboard/models/__init__.py
dashboard/models/apps.py
dashboard/models/user.py
requirements.txt

There was some discussion about schemas on GitHub and Slack. This commit takes some of those thoughts and codifies them.
The types defined in `dashboard.models.apps` are copied to the configuration repository, where they're used in the tests.
A Better :tm: solution would maybe include publishing a package so we don't need to depend on copying/pasting the schemas, but for now this'll do.
Jira: [IAM-950](https://mozilla-hub.atlassian.net/browse/IAM-950)

models Add a schema for application definitions

---

clouddeploy/sso-dashboard-dev.template.yaml
clouddeploy/sso-dashboard-prod.template.yaml
clouddeploy/sso-dashboard-staging.template.yaml
compose.yml
dashboard/config.py
env.example
tests/test_vanity.py

I finally got annoyed enough to change things, removing requirements for tooling (wrappers around running flask or some local env manager).
Jira: [IAM-950](https://mozilla-hub.atlassian.net/browse/IAM-950)

Minor fixes for local development
