mozilla-iam/sso-dashboard

dashboard/auth.py

force ssl redirect URI by updating OIDC Object

---

dashboard/app.py
dashboard/op/yaml_loader.py

Adds a dynamic router based on a list of vanity_urls present in apps.yml

add vanity URL dyanmic routing closes #37

---

ansible/container.yml
cloudformation/dashboard.yml

Reverts mozilla-iam/sso-dashboard#54

Revert "Fix mozillians api key"

---

dashboard/app.py
dashboard/static/js/ga.js
dashboard/templates/layout.html

That would give us the ability to track outbound links

Enable Google Tag Manager

---

dashboard/static/css/base.scss
dashboard/templates/dashboard.html
dashboard/templates/layout.html
dashboard/user.py
env.example

* Fix fonts paths
* Simplify avatar code to handle default avatar on the frontend

Fix all paddings on appbar and footer

---

dashboard/static/css/base.scss

* Align left on focus
* Hide placeholder on focus

Adjust search alignment

---

dashboard/templates/layout.html

Update the get help link with preferred text.

s/Help desk/ with alternate text

---

dashboard/templates/layout.html

Add a deep link to SN to auto open a helpdesk ticket instead of pointing them to the service catalog.

Auto open helpdesk ticket

---

dashboard/static/css/base.scss
dashboard/static/img/feedback.svg
dashboard/templates/layout.html

* Use flexbox for footer icons
* Fixes #44

Add feedback button

---

dashboard/app.py
dashboard/static/css/base.scss
dashboard/templates/404.html
dashboard/templates/layout.html

* Fixes mozilla/iam-project-backlog/issues/103

Add 404 page

---

dashboard/app.py

CSP for Google Tag Manager

---

ansible/container.yml
dashboard/app.py

CAB https://mozilla.service-now.com/sp?id=form&table=change_request&sys_id=8f166c3c132ab200472ed2f18144b0c1

Deploy CSP Changes to Production from CHG0011687

---

dashboard/static/css/base.scss

* Decrease spacing between app tiles
* Use smaller app icons
* Fix coming-soon text color

[Fixes #101] Increase icons desnity

---

dashboard/app.py

definition
See also https://github.com/mozilla-iam/auth0-deploy/pull/124
See also https://github.com/mozilla/iam-project-backlog/issues/161

Add https://sso.mozilla.com/claim as a route, 302 to our schema

---

dashboard/app.py

Allow gravatar in csp rules.

---

cloudformation/us-west-2.yml

- Since we're fork lifting the instances target groups need new names.

update cfn template to have new names for target groups

---

dashboard/templates/layout.html

Changed from mozilla-community to mozilla.org

Changed Discourse URL in Footer

---

dashboard/app.py

Temporarily have both domains while we add the CDN

Add cdn.mozillians.org to img-src CSP

---

.travis.yml
ansible/roles/dashboard/tasks/main.yml
buildspec.yml
cloudformation/us-west-2.yml
dashboard/app.py
dashboard/auth.py
dashboard/config.py
dashboard/op/yaml_loader.py
dashboard/s3.py
dashboard/static/js/base.js
dashboard/templates/dashboard.html
dashboard/templates/layout.html
dashboard/user.py
dashboard/utils.py
dashboard/vanity.py
requirements.txt
tests/data/userinfo.json
tests/test_config.py
tests/test_user.py
tests/test_yaml_loader.py

This PR is the result of some of the Sprint #15 work items. 
* Switch to custom backport of Flask PyOIDC .
* Get tests passing.

Land Light Refactor and PyOIDC Fork in Prod

---

ansible/roles/dashboard/tasks/main.yml
dashboard/models/user.py

Fix avatar logic to not fetch avatar if URL is None type.
Fix ansible play that was rebased over.

Staging hotfix for user_url is None

---

ansible/roles/dashboard/tasks/main.yml
dashboard/auth.py
dashboard/models/alert.py
requirements.txt

Handle condition where version can not be parsed out of firefox
Revert to latest pyoidc and flask-pyoidc

De-Patch the Dashboard

---

dashboard/static/css/base.scss

This is based on the new Mozilla brand guidelines - fixes #231

Update alerts colors

---

dashboard/templates/dashboard.html

Swap Nightly for Beta

---

dashboard/auth.py

Fixes @edmorley's https://github.com/mozilla-iam/sso-dashboard/issues/213

Clarified 'most secure account' error message

---

dashboard/static/js/base.js

Check helpfulness with document.activeElement

---

dashboard/templates/dashboard.html

Only show unread badge if there are visible unreads

---

dashboard/models/tile.py
dashboard/models/user.py
dashboard/op/yaml_loader.py
dashboard/templates/dashboard.html
dashboard/templates/notifications.html

add method back to fetch from s3. change group structure to also support non-OIDC conformant and mozilla claims.  hide button to escalte to MOC.

hide escalate button

---

dashboard/static/css/base.scss
dashboard/static/js/base.js

Make CSS and JS lint

---

dashboard/app.py
dashboard/config.py
dashboard/models/user.py
dashboard/templates/forbidden.html

Add person api information to info endpoint
Remove mozillians api key and url from config
Add person api avatar retrieval
Remove access token from info endpoint
Improves UX for issue #205 - cc @gene1wood

Sprint F Work and Minor Fixes for OIDC Conformant

---

dashboard/app.py
dashboard/config.py
dashboard/models/user.py
dashboard/templates/forbidden.html

Modify firstName retrieval to come from id_vault.

Avatar and ux

---

dashboard/app.py
dashboard/config.py
dashboard/models/user.py
dashboard/templates/forbidden.html
tests/test_user.py

* Remove access token from info endpoint
Add person api information to info endpoint
Remove mozillians api key and url from config
Add person api avatar retrieval
* Closes #260
Hotfix missing data in userinfo to pass to firefox alert rules.

Sprint F Work and Minor Fixes for OIDC Conformant (#259)

---

dashboard/templates/signout.html

This fixes #277 
@andrewkrug we could, of course, put CSS in a separate file and make this template `extend` layout.html, but… its CSS and structure is a bit of an exception to the rest of it. What if this is the only page that looks like this? Looking forward to hearing your thoughts

Replace logout page by NLX style logout page

---

dashboard/csp.py
dashboard/person.py
dashboard/templates/dashboard.html
dashboard/templates/notifications.html

remove escalate button, add logic to send queries to dev person api when hooked up to auth0 dev, add mozillians CDN to CSP

multiple fixes

---

dashboard/auth.py

see also https://github.com/mozilla-iam/auth0-deploy/pull/194

support expiration of access msg

---

dashboard/models/user.py
dashboard/static/css/base.scss
dashboard/templates/notifications.html

This adds the ability for an alert to provide additional details in the "details" key, and the notifications view will automatically display the fields.

Add extra details to alert in notifications

---

requirements.txt

add gevent back to reqs

---

dashboard/app.py
requirements.txt

adds a simple Prometheus exporter

---

dashboard/app.py
dashboard/models/user.py

add prometheus monitoring to sso-dashboard configuration namespace

---

dashboard/config.py

This allows me to test the deployments in Kubernetes before I change any DNS records. It may also be useful in the future when we migrate the CloudFront distributions and corresponding origins to the new account.
NOTE: "Restrict who can push to this …

enables configuration of CDN address

---

k8s/Chart.yaml
k8s/templates/00-namespace.yaml
k8s/templates/deployment.yaml
k8s/templates/ingress.yaml
k8s/templates/service.yaml
k8s/values.yaml
k8s/values/dev.yaml
k8s/values/prod.yaml
k8s/values/staging.yaml

adding Kubernetes YAML for deployment, service and ingress

---

dashboard/__init__.py

handle itemNotfound

---

dashboard/__init__.py

fix return to always be something

---

buildspec-k8s.yml

adding buildspec for Kubernetes

---

ansible/roles/dashboard/files/nginx/start.sh

allowing Gunicorn worker override through env variables

---

cloudformation/us-west-2.yml

Remove regions that we no longer use

---

dashboard/data/apps.yml

Add new group exclusively for mozdefqa

---

dashboard/models/tile.py

fix app.py process hup

---

dashboard/data/apps.yml
dashboard/models/tile.py

Deploy process hup fixes to prod

---

k8s/values/staging.yaml

bump dev replicas to two pods

---

k8s/templates/deployment.yaml

bump CPU and mem reserved in order to increase worker count

---

dashboard/app.py
dashboard/models/alert.py
dashboard/models/user.py
requirements-dev.txt
requirements.txt
tests/test_alerts.py

Note:  This will need to merge before #380 and then rebase into that branch.

fix flake8 errors introduced by black formatter

---

k8s/templates/ingress-controller.yaml

Create an ingress-controller per namespace

---

.vscode/settings.json
Dockerfile
Makefile
buildspec-k8s.yml
dashboard/app.py
dashboard/auth.py
dashboard/config.py
dashboard/data/apps.yml
dashboard/logging.yml
dashboard/oidc_auth.py
requirements.txt
tests/test_error.py

fix yaml load to be safe load

---

dashboard/config.py

fix preferred url

---

Makefile

try to fix dpkg

---

Makefile

should fix trusty install

---

Makefile

back to xenial

---

Makefile

move to amzn linux for codebuild

---

Makefile
buildspec-k8s.yml

update make targets

---

buildspec-k8s.yml

include runtimes

---

dashboard/data/apps.yml

Remove old MOC access
Use datacenter agnostic URLs
Allow QA group access to both QA servers
NOTE: "Restrict who can push to this branch" is effectively the control by which you may allow specific teams to write issues without being able to change …

Make MozDef QA and Production Consistent

---

dashboard/templates/dashboard.html

Minor change to the link in the upper right hand corner.

Change link for settings to point to people.m.o

---

README.md

Document dashboard deployment process

---

Dockerfile
Makefile
dashboard/app.py
k8s/Chart.yaml
requirements.txt

This is running at sso.allizom.org. @mozfreddyb can you verify you are no longer seeing the http redirect there? I was able to confirm the behavior via curl but was never able to reproduce in a browser. 
```bash
$ curl -X GET -I -L sso.allizom.org                                                                                                                                                
HTTP/1.1 308 Permanent Redirect                                                                                                                                                                                                                               
Server: nginx/1.15.10 …
```

Remove http redirect

---

Dockerfile
Makefile
dashboard/app.py
k8s/Chart.yaml
requirements.txt

Closed previous PR in favor of this one. I am manually pulling in the commits from `master` I want instead of merging `master` to `production`. Commits are signed.

Production redirect patch

---

.github/workflows/main.yml
.pre-commit-config.yaml
clouddeploy.yaml
compose.yml
package-lock.json
package.json

This PR includes some clean up work from the big revamp done recently. This include:
* updating the npm packages
* adding docker compose file for local testing
* a clouddeploy yaml for infra reference
* fix the GHA trigger branch

Clean up from revamp

---

dashboard/app.py
requirements.txt

This sets up a gcp cloud logger in order to get better log integration

Enable gcp cloud logging

---

dashboard/app.py
dashboard/config.py
dashboard/models/tile.py
dashboard/models/user.py
tests/test_error.py

IAM-1256 Remove Alerts and Notifications functions within SSO Dashbord

---

dashboard/templates/dashboard.html

- removed coming soon and access request from menu

IAM-1293 Remove notifications link in people.m.o dropdown menu

---

dashboard/oidc_auth.py

Reformatted file to correct failing lint.

IAM-1269 reformatted oidc_auth.py

---

dashboard/oidc_auth.py

changes import of josepy.error that was breaking application.
Verified local development environment comes up cleanly.

IAM-1269 JWT 500 errors

---

dashboard/static/js/base.js

Activate tile link on searchbox enter key if only one visible

---

dashboard/__init__.py
dashboard/app.py
dashboard/oidc_auth.py

Full mypy support will be coming soon!

Get working with mypy

---

tests/data/apps.yml
tests/test_vanity.py

We're now up to 54% test coverage!
Jira: [OPS-1443](https://mozilla-hub.atlassian.net/browse/IAM-1443)

Tests for dashboard.vanity.Router

---

dashboard/app.py

Jira: [IAM-1493](https://mozilla-hub.atlassian.net/browse/IAM-1493)
---
In hindsight: why didn't I do this before?!

redirect_uri used http, so use PREFERRED_URL_SCHEME

---

requirements.txt

Spawned from https://github.com/mozilla-iam/sso-dashboard/pull/544
Jira: Untracked

dep Upgrade pyOpenSSL -> 25.0.0 and cryptography -> 44.0.1

---

clouddeploy/sso-dashboard-dev.template.yaml

Jira: [IAM-1492](https://mozilla-hub.atlassian.net/browse/IAM-1492)

Use the custom domain for dev IdP

---

dashboard/models/user.py

Jira: [IAM-950](https://mozilla-hub.atlassian.net/browse/IAM-950)

dashboard typecheck itself was not imported

---

dashboard/models/user.py
dashboard/op/yaml_loader.py
dashboard/templates/dashboard.html
tests/op/test_yaml_loader.py

Letting the "view" deal with truncation, instead of our data model.

Fix truncation and data model

---

dashboard/oidc_auth.py

Reported by @krutkmasha.
Jira: Untracked

typo s/emal/email/

---

clouddeploy/sso-dashboard-prod.template.yaml

See also:
* https://github.com/mozilla-iam/iam/pull/31
Jira: IAM-1492

Use custom domain

---

clouddeploy/sso-dashboard-dev.template.yaml

Jira: [IAM-1768](https://mozilla-hub.atlassian.net/browse/IAM-1768)

feat(iam): Use a custom domain on dev
